### ISSUE TITLE
prodigy optimizer dont apply changes to lora weights

### ISSUE THREAD

**Issue by drimeF0** [kohya-ss/sd-scripts#1343]
![image](https://github.com/kohya-ss/sd-scripts/assets/67423319/26388468-8230-46fc-906b-82e31b20275b)
the command I used to run the script:
```bash
%cd /content/sd-scripts
!source /content/venv/bin/activate;accelerate launch "sdxl_train_network.py" --in_json "/content/dataset_lat.json" --console_log_simple  --pretrained_model_name_or_path "/content/model.safetensors" --dataset_repeats "1" --train_data_dir "/content/dataset" --output_dir "/content/drive/MyDrive/out" --network_alpha "32"  --network_dim "32" --save_model_as safetensors --network_module networks.lora --output_name "last" --no_half_vae --learning_rate "1.0" --train_batch_size "5" --max_train_epochs "32" --save_every_n_steps 30 --mixed_precision "fp16" --save_precision "fp16" --optimizer_type "prodigy"  --mem_eff_attn --gradient_checkpointing --scale_weight_norms 1 --full_fp16 --xformers --sample_sampler euler_a --sample_prompts "/content/prompt.txt" --sample_every_n_steps 30  --network_train_unet_only --cache_text_encoder_outputs --lowram
```
the images that are generated every 30 steps are exactly the same

**Comment by DKnight54** [comment]
I see you are running the script in colab and is using the --full_fp16 to get it to work. unfortunately, from my personal experience, something about full_fp16 seems to wreck havoc on adaptive optimizers. I generally just end up using adafactor on constant LR mode to train LoRAs on colab.

However, I have some good news. It takes some tweaking, but it's possible to run the same script you are probably using in Google Colab in **[Kaggle](https://www.kaggle.com/)** with a free account, and you get 2 T4s instead of one. The higher RAM budget (NOT VRAM) in Kaggle's enviroment makes it possible to run FP16 training without using full_fp16 and I've been getting good training results.

**Comment by drimeF0** [comment]
> I see you are running the script in colab and is using the --full_fp16 to get it to work. unfortunately, from my personal experience, something about full_fp16 seems to wreck havoc on adaptive optimizers. I generally just end up using adafactor on constant LR mode to train LoRAs on colab.


Thank you, I will close this issue then
