### ISSUE TITLE
wandb logging parameters error: Dataset_Repeats not correct

### ISSUE THREAD

**Issue by rafstahelin** [kohya-ss/sd-scripts#1408]
I have my training images set to 10 repeats using network training script to 10_token class, but when logging to WandB the run shows dataset_repeat = 1. Might be logging the regularization repeats. Still this is wrong

**Comment by rockerBOO** [comment]
This is probably because it's capturing the argument value for the script `args.dataset_repeat` but your value is part of the datasets subset which may be in a different place. Since this supports multiple datasets/subsets it might be tricky to get this extracted effectively to a single value. 

It may be appropriate to extract it if it's a single dataset value though.

**Comment by rafstahelin** [comment]
@rockerBOO  how do I extract it? I usually only use one dataset no subsets (until now). Also, would be good to get the path and folder used for the training data. I don't see it in wandb either

**Comment by rockerBOO** [comment]
Under `ss_dataset_dirs` there is `n_repeats` in the json.
